// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v5.28.3
// source: three/proto/beef.proto

package beef

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BeefRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *BeefRequest) Reset() {
	*x = BeefRequest{}
	mi := &file_three_proto_beef_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeefRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeefRequest) ProtoMessage() {}

func (x *BeefRequest) ProtoReflect() protoreflect.Message {
	mi := &file_three_proto_beef_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeefRequest.ProtoReflect.Descriptor instead.
func (*BeefRequest) Descriptor() ([]byte, []int) {
	return file_three_proto_beef_proto_rawDescGZIP(), []int{0}
}

func (x *BeefRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type BeefResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BeefCount map[string]int32 `protobuf:"bytes,1,rep,name=beef_count,json=beefCount,proto3" json:"beef_count,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
}

func (x *BeefResponse) Reset() {
	*x = BeefResponse{}
	mi := &file_three_proto_beef_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeefResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeefResponse) ProtoMessage() {}

func (x *BeefResponse) ProtoReflect() protoreflect.Message {
	mi := &file_three_proto_beef_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeefResponse.ProtoReflect.Descriptor instead.
func (*BeefResponse) Descriptor() ([]byte, []int) {
	return file_three_proto_beef_proto_rawDescGZIP(), []int{1}
}

func (x *BeefResponse) GetBeefCount() map[string]int32 {
	if x != nil {
		return x.BeefCount
	}
	return nil
}

var File_three_proto_beef_proto protoreflect.FileDescriptor

var file_three_proto_beef_proto_rawDesc = []byte{
	0x0a, 0x16, 0x74, 0x68, 0x72, 0x65, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x62, 0x65,
	0x65, 0x66, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x62, 0x65, 0x65, 0x66, 0x22, 0x21,
	0x0a, 0x0b, 0x42, 0x65, 0x65, 0x66, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78,
	0x74, 0x22, 0x8e, 0x01, 0x0a, 0x0c, 0x42, 0x65, 0x65, 0x66, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x40, 0x0a, 0x0a, 0x62, 0x65, 0x65, 0x66, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x62, 0x65, 0x65, 0x66, 0x2e, 0x42, 0x65,
	0x65, 0x66, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x42, 0x65, 0x65, 0x66, 0x43,
	0x6f, 0x75, 0x6e, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x09, 0x62, 0x65, 0x65, 0x66, 0x43,
	0x6f, 0x75, 0x6e, 0x74, 0x1a, 0x3c, 0x0a, 0x0e, 0x42, 0x65, 0x65, 0x66, 0x43, 0x6f, 0x75, 0x6e,
	0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02,
	0x38, 0x01, 0x32, 0x43, 0x0a, 0x0b, 0x42, 0x65, 0x65, 0x66, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x65,
	0x72, 0x12, 0x34, 0x0a, 0x09, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x42, 0x65, 0x65, 0x66, 0x12, 0x11,
	0x2e, 0x62, 0x65, 0x65, 0x66, 0x2e, 0x42, 0x65, 0x65, 0x66, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x12, 0x2e, 0x62, 0x65, 0x65, 0x66, 0x2e, 0x42, 0x65, 0x65, 0x66, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x12, 0x5a, 0x10, 0x74, 0x68, 0x72, 0x65, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x62, 0x65, 0x65, 0x66, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_three_proto_beef_proto_rawDescOnce sync.Once
	file_three_proto_beef_proto_rawDescData = file_three_proto_beef_proto_rawDesc
)

func file_three_proto_beef_proto_rawDescGZIP() []byte {
	file_three_proto_beef_proto_rawDescOnce.Do(func() {
		file_three_proto_beef_proto_rawDescData = protoimpl.X.CompressGZIP(file_three_proto_beef_proto_rawDescData)
	})
	return file_three_proto_beef_proto_rawDescData
}

var file_three_proto_beef_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_three_proto_beef_proto_goTypes = []any{
	(*BeefRequest)(nil),  // 0: beef.BeefRequest
	(*BeefResponse)(nil), // 1: beef.BeefResponse
	nil,                  // 2: beef.BeefResponse.BeefCountEntry
}
var file_three_proto_beef_proto_depIdxs = []int32{
	2, // 0: beef.BeefResponse.beef_count:type_name -> beef.BeefResponse.BeefCountEntry
	0, // 1: beef.BeefCounter.CountBeef:input_type -> beef.BeefRequest
	1, // 2: beef.BeefCounter.CountBeef:output_type -> beef.BeefResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_three_proto_beef_proto_init() }
func file_three_proto_beef_proto_init() {
	if File_three_proto_beef_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_three_proto_beef_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_three_proto_beef_proto_goTypes,
		DependencyIndexes: file_three_proto_beef_proto_depIdxs,
		MessageInfos:      file_three_proto_beef_proto_msgTypes,
	}.Build()
	File_three_proto_beef_proto = out.File
	file_three_proto_beef_proto_rawDesc = nil
	file_three_proto_beef_proto_goTypes = nil
	file_three_proto_beef_proto_depIdxs = nil
}
