// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: three/proto/beef.proto

package beef

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BeefCounter_CountBeef_FullMethodName = "/beef.BeefCounter/CountBeef"
)

// BeefCounterClient is the client API for BeefCounter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BeefCounterClient interface {
	CountBeef(ctx context.Context, in *BeefRequest, opts ...grpc.CallOption) (*BeefResponse, error)
}

type beefCounterClient struct {
	cc grpc.ClientConnInterface
}

func NewBeefCounterClient(cc grpc.ClientConnInterface) BeefCounterClient {
	return &beefCounterClient{cc}
}

func (c *beefCounterClient) CountBeef(ctx context.Context, in *BeefRequest, opts ...grpc.CallOption) (*BeefResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BeefResponse)
	err := c.cc.Invoke(ctx, BeefCounter_CountBeef_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BeefCounterServer is the server API for BeefCounter service.
// All implementations must embed UnimplementedBeefCounterServer
// for forward compatibility.
type BeefCounterServer interface {
	CountBeef(context.Context, *BeefRequest) (*BeefResponse, error)
	mustEmbedUnimplementedBeefCounterServer()
}

// UnimplementedBeefCounterServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBeefCounterServer struct{}

func (UnimplementedBeefCounterServer) CountBeef(context.Context, *BeefRequest) (*BeefResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CountBeef not implemented")
}
func (UnimplementedBeefCounterServer) mustEmbedUnimplementedBeefCounterServer() {}
func (UnimplementedBeefCounterServer) testEmbeddedByValue()                     {}

// UnsafeBeefCounterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BeefCounterServer will
// result in compilation errors.
type UnsafeBeefCounterServer interface {
	mustEmbedUnimplementedBeefCounterServer()
}

func RegisterBeefCounterServer(s grpc.ServiceRegistrar, srv BeefCounterServer) {
	// If the following call pancis, it indicates UnimplementedBeefCounterServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BeefCounter_ServiceDesc, srv)
}

func _BeefCounter_CountBeef_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BeefRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BeefCounterServer).CountBeef(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BeefCounter_CountBeef_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BeefCounterServer).CountBeef(ctx, req.(*BeefRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BeefCounter_ServiceDesc is the grpc.ServiceDesc for BeefCounter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BeefCounter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "beef.BeefCounter",
	HandlerType: (*BeefCounterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CountBeef",
			Handler:    _BeefCounter_CountBeef_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "three/proto/beef.proto",
}
